apiVersion: v1
kind: PersistentVolume
metadata:
  name: appdisk
  namespace: bc-client
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/private/tmp/app-data"