apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-client
  namespace: bc-client
  labels:
    app: bc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bc-client
  template:
    metadata:
      labels:
        app: bc-client
    spec:
      containers:
      - name: bc-client
        image: syabz03/bc-client
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
          name: http-node
        - containerPort: 443
          name: https-node
        - containerPort: 4444
          name: flask-tcp
        volumeMounts:
        - name: bc-client-storage
          mountPath: "/app-data"
      volumes:
        - name: bc-client-storage
          persistentVolumeClaim:
            claimName: appclaim