apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appclaim
  namespace: bc-client
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi