apiVersion: v1
kind: Service
metadata:
  labels:
    app: bc-server
  name: bc-server
  namespace: bc-server
spec:
  type: NodePort
  ports:
  - port: 80
    name: http-node
  - port: 443
    name: https-node
  selector:
    app: bc-server