apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serverclaim
  namespace: bc-server
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi