apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-py-fb
  namespace: k8-py-fb
  labels:
    app: k8-py-fb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-py-fb
  template:
    metadata:
      labels:
        app: k8-py-fb
    spec:
      containers:
      - name: k8-py-fb
        image: k8-py-fb:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
          name: http-node
        - containerPort: 443
          name: https-node
        volumeMounts:
        - name: k8-py-fb-storage
          mountPath: "/app-data"
      volumes:
        - name: k8-py-fb-storage
          persistentVolumeClaim:
            claimName: appclaim