apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8-py-fb
  name: k8-py-fb
  namespace: k8-py-fb
spec:
  type: NodePort
  ports:
  - port: 80
    name: http-node
  - port: 443
    name: https-node
  selector:
    app: k8-py-fb