apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appclaim
  namespace: k8-py-fb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi