apiVersion: v1
kind: PersistentVolume
metadata:
  name: appdisk
  namespace: k8-py-fb
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp"