apiVersion: v1
kind: PersistentVolume
metadata:
  name: serverdisk
  namespace: bc-server
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp"